### ISSUE TITLE
Move on public link page

### ISSUE THREAD

**Issue by scolebrook** [eotryx/oc_files_mv#24]
The move action is displayed on public link pages. But the functionality can't be used and doesn't work. I've hidden it with css in mv.css.
``` css
#body-public .action-move {
    display: none !important;
}
```
There might be a better way to hide a file action on a public page, but this gets the job done for those who need it.
